import Navbar from "@/components/layout/Navbar";
import Link from "next/link";

const LAST_UPDATED = "March 31, 2026";
const COMPANY = "Delphi Oracle";
const EMAIL = "legal@delphioracle.ai";

interface Section {
  id: string;
  title: string;
  content: React.ReactNode;
}

const sections: Section[] = [
  {
    id: "agreement",
    title: "Agreement to Terms",
    content: (
      <p>By accessing or using Delphi Oracle (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. These Terms apply to all visitors, users, and others who access the Service.</p>
    ),
  },
  {
    id: "description",
    title: "Description of Service",
    content: (
      <p>Delphi Oracle is an AI-powered decision simulation platform that generates probability-weighted future scenarios based on user-provided profile data and decisions. The Service allows users to explore branching timelines, combine multiple life domains, and analyze potential outcomes. Simulations are speculative in nature and are intended as exploratory tools, not definitive predictions or professional advice of any kind.</p>
    ),
  },
  {
    id: "accounts",
    title: "User Accounts",
    content: (
      <ul className="list-disc list-inside space-y-2">
        <li>You must provide accurate and complete information when creating an account.</li>
        <li>You are responsible for maintaining the security of your account credentials.</li>
        <li>You must notify us immediately of any unauthorized access to your account.</li>
        <li>You must be at least 16 years old to use the Service.</li>
        <li>One person may not maintain more than one free account.</li>
      </ul>
    ),
  },
  {
    id: "acceptable-use",
    title: "Acceptable Use",
    content: (
      <>
        <p className="mb-3">You agree not to use the Service to:</p>
        <ul className="list-disc list-inside space-y-2">
          <li>Generate content that is harmful, threatening, abusive, harassing, or defamatory toward any person.</li>
          <li>Simulate illegal activities, plans for violence, or content that violates applicable law.</li>
          <li>Attempt to reverse-engineer, scrape, or extract the underlying AI prompts or model architecture.</li>
          <li>Resell or sublicense access to the Service without our written permission.</li>
          <li>Circumvent rate limits, access controls, or security measures.</li>
          <li>Create accounts through automated means or bots.</li>
          <li>Use the Service to deceive others by presenting AI-generated simulations as factual forecasts.</li>
        </ul>
      </>
    ),
  },
  {
    id: "api-keys",
    title: "API Keys and Third-Party Services",
    content: (
      <>
        <p className="mb-3">You may connect third-party AI provider keys (e.g., Anthropic, OpenAI) to the Service. By doing so:</p>
        <ul className="list-disc list-inside space-y-2">
          <li>You confirm you have the right to use those keys under the provider&apos;s terms of service.</li>
          <li>You accept that your simulation inputs are transmitted to the relevant AI provider and are subject to their privacy policy and terms.</li>
          <li>We store your API keys in encrypted form (AES-256-GCM) and are not responsible for costs incurred through your connected AI provider accounts.</li>
          <li>You can remove stored keys at any time from Settings &rarr; AI Providers.</li>
        </ul>
      </>
    ),
  },
  {
    id: "intellectual-property",
    title: "Intellectual Property",
    content: (
      <>
        <p className="mb-3"><strong>Your content:</strong> You retain full ownership of any profile data, decisions, and simulation content you generate using the Service. We claim no intellectual property rights over your content.</p>
        <p className="mb-3"><strong>License to us:</strong> By using the Service, you grant us a limited, non-exclusive, royalty-free license to store and process your content solely to provide the Service to you. We do not use your content to train AI models.</p>
        <p><strong>Our content:</strong> The Delphi Oracle platform, branding, UI, and underlying software are owned by us and protected by copyright and other intellectual property laws. You may not copy, modify, or distribute our platform without permission.</p>
      </>
    ),
  },
  {
    id: "disclaimers",
    title: "Disclaimers",
    content: (
      <>
        <p className="mb-3">THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTY OF ANY KIND. WE EXPRESSLY DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
        <p className="mb-3"><strong>AI outputs are speculative, not advice.</strong> Simulations generated by Delphi Oracle are probabilistic explorations of possible futures based on AI inference. They are not financial, legal, medical, psychological, or professional advice of any kind. Do not make major life decisions based solely on simulation output.</p>
        <p>We do not guarantee the accuracy, completeness, or reliability of any simulation result. The future is inherently uncertain — the Oracle is a thinking tool, not a crystal ball.</p>
      </>
    ),
  },
  {
    id: "liability",
    title: "Limitation of Liability",
    content: (
      <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL DELPHI ORACLE, ITS AFFILIATES, OFFICERS, EMPLOYEES, OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES — INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, OR GOODWILL — ARISING FROM YOUR USE OF OR INABILITY TO USE THE SERVICE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE MONTHS PRECEDING THE CLAIM, OR $50, WHICHEVER IS GREATER.</p>
    ),
  },
  {
    id: "termination",
    title: "Termination",
    content: (
      <>
        <p className="mb-3">We may suspend or terminate your account at any time if we believe you have violated these Terms, without prior notice or liability.</p>
        <p>You may delete your account at any time from Settings &rarr; Data &amp; Privacy &rarr; Delete account. Upon deletion, all your data is permanently removed from our systems within 30 days, except where retention is required by law.</p>
      </>
    ),
  },
  {
    id: "changes",
    title: "Changes to Terms",
    content: (
      <p>We reserve the right to modify these Terms at any time. When we make material changes, we will update the &quot;Last updated&quot; date at the top of this page and notify registered users by email. Your continued use of the Service after changes take effect constitutes acceptance of the revised Terms.</p>
    ),
  },
  {
    id: "contact",
    title: "Contact",
    content: (
      <p>Questions about these Terms? Email us at <a href={`mailto:${EMAIL}`} className="text-oracle-400 hover:underline">{EMAIL}</a>.</p>
    ),
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-void-950 flex flex-col">
      <Navbar />
      <div className="flex-1 max-w-3xl w-full mx-auto px-6 py-12">
        <div className="mb-10">
          <p className="text-xs font-medium text-oracle-500 uppercase tracking-widest mb-3">Legal</p>
          <h1 className="text-3xl font-bold text-text-primary mb-2">Terms of Service</h1>
          <p className="text-text-muted text-sm">Last updated {LAST_UPDATED}</p>
        </div>

        <div className="space-y-10">
          {sections.map((s) => (
            <section key={s.id} id={s.id}>
              <h2 className="text-base font-semibold text-text-primary mb-3 pb-2 border-b border-border-subtle">
                {s.title}
              </h2>
              <div className="text-sm text-text-secondary leading-relaxed space-y-2">
                {s.content}
              </div>
            </section>
          ))}
        </div>

        <div className="mt-12 pt-8 border-t border-border-subtle flex items-center justify-between text-sm text-text-muted">
          <span>{COMPANY} · {LAST_UPDATED}</span>
          <Link href="/privacy" className="text-oracle-400 hover:text-oracle-300 transition-colors">Privacy Policy &rarr;</Link>
        </div>
      </div>
    </div>
  );
}
